name: Laravel Deployment

on:
  push:
    branches:
      - main  # Replace with your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'  # Adjust based on your PHP version
        extensions: mbstring, pdo, bcmath
        ini-values: post_max_size=256M, upload_max_filesize=256M

    - name: Install Composer dependencies
      run: composer install --no-dev --optimize-autoloader

    - name: Run Laravel commands
      run: |
        php artisan migrate --force
        php artisan config:cache
        php artisan route:cache
        php artisan view:cache

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_KEY }}
        script: |
          cd /var/www/starter/laravel-starter-main
          git pull origin main
          composer install --no-dev --optimize-autoloader
          php artisan migrate --force
          php artisan config:cache
