name: Deploy Node.js App

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Run on the latest Ubuntu environment

      steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout the repository

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3  # Set up SSH for deployment
        with:
          ssh-private-key: ${{ secrets.SERVER_KEY }}  # GitHub secret with SSH private key

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no root@23.88.98.228 "cd /var/www/starter/laravel-starter-main && git pull && npm install && pm2 restart app"  # Adjust with your app's path and commands
