name: Deploy Laravel Project

on:
  push:
    branches:
      - main  # or the branch you want to trigger deployment on

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SERVER_KEY }}

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no root@arlind.devops99.pro "cd /var/www/starter/laravel-starter-main && git pull && composer install && php artisan migrate"
